services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/coatstore:/app/coatstore
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=coatstore
      - DB_USER=postgres
      - DB_PASSWORD=Mario228
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: coatstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mario228
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: